initial bhyve ppt grub support v2 / based on https://blog.movementarian.org/2018/10/pci-pass-through-support-with-bhyve-and.html\?m\=0

diff --git a/tools/images/make_image b/tools/images/make_image
--- a/tools/images/make_image
+++ b/tools/images/make_image
@@ -207,6 +207,19 @@ if ! $PFEXEC /sbin/mount -F pcfs -o 'foldcase,noatime,hidden,clamptime,rw' \
 fi
 
 #
+# Create the bhyve ppt overlay directory and files within the image.
+#
+if ! mkdir -p "$g_mount_point/overlay/etc"; then
+	fatal 'could not create bhyve ppt overlay directory within image'
+fi
+if ! touch "$g_mount_point/overlay/etc/ppt_aliases"; then
+	fatal 'could not create bhyve ppt overlay ppt_aliases file within image'
+fi
+if ! touch "$g_mount_point/overlay/etc/ppt_matches"; then
+	fatal 'could not create bhyve ppt overlay ppt_matches file within image'
+fi
+
+#
 # Create the grub directory within the image.
 #
 if ! mkdir -p "$g_mount_point/boot/grub"; then
